/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Estructuras.*;
import Nodos.*;
import ProyectObj.*;
import java.awt.*;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.graphstream.graph.*;
import org.graphstream.graph.implementations.*;
import org.graphstream.ui.swing_viewer.*;
import org.graphstream.ui.view.*;
import java.time.Clock;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTree;
import javax.swing.SwingUtilities;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
/**
 *
 * @author usuario
 */
public class GUI extends javax.swing.JFrame {

    
    private Clock timer;
    private BinaryHeap<Documento> colaImpresion;
    private Lista<Usuario> listaUsuarios;
    private Graph monticulo;
    private File currentFile;
    private Usuario currentUser;
    DefaultTreeModel modelo;
    DefaultMutableTreeNode root;
    /**
     * Creates new form GUI
     */
    public GUI() {
        timer = Clock.systemDefaultZone();
        currentFile = null;
        monticulo = new SingleGraph("Monticulo", false, true);
        colaImpresion = new BinaryHeap(20);
        listaUsuarios = new Lista();
        initComponents();
        usersTree.setRootVisible(false);
        sistemaPrincipal.setVisible(false);
        userSelection.setVisible(true);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        agregarUsuarioVisible(false,"");
        userSelection.validate();
        prioridadAltaButton.setActionCommand("prioridad_alta");
        prioridadMediaButton.setActionCommand("prioridad_media");
        prioridadBajaButton.setActionCommand("prioridad_baja");
    }

    private void setUserOptions() {
        elegirUsuario.removeAll();
        for (int i=0; i < listaUsuarios.getLength(); i++) {
            elegirUsuario.insert(listaUsuarios.getElmenetAtIndex(i).getName(), i);
        }
    }
    
    private void agregarUsuarioVisible(boolean show, String label) {
        tiposPrioridad.clearSelection();
        nombreUsuario.setText("");
        prioridadAltaButton.setVisible(show);
        prioridadMediaButton.setVisible(show);
        prioridadBajaButton.setVisible(show);
        confirmarAgregar.setVisible(show);
        cancelarAgregar.setVisible(show);
        nombreUsuario.setVisible(show);
        addUserLabel.setVisible(show);
        SelectionLabel.setText(label);
    }
    
    private void setUserDisplay() {
//        usersDisplay.removeAll();
        modelo = (DefaultTreeModel) usersTree.getModel();
        root = (DefaultMutableTreeNode) modelo.getRoot();
        root.removeAllChildren();
        
        root.removeAllChildren();
        for (Usuario u:listaUsuarios) {
            DefaultMutableTreeNode usuario = new DefaultMutableTreeNode(u.getName());
            root.add(usuario);
            for (Documento d: u.getDocumentos()) {
                DefaultMutableTreeNode doc = new DefaultMutableTreeNode(d.getName());
                usuario.add(doc);
                doc.add(new DefaultMutableTreeNode(d.getType()));
                doc.add(new DefaultMutableTreeNode(d.getSize() + "páginas"));
            }
        }
        modelo.reload();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tiposPrioridad = new javax.swing.ButtonGroup();
        textArea1 = new java.awt.TextArea();
        displaysPane = new javax.swing.JTabbedPane();
        treePanel = new javax.swing.JScrollPane();
        usersTree = new javax.swing.JTree();
        graphDisplay = new javax.swing.JPanel();
        colaDisplay = new javax.swing.JPanel();
        panelFondo = new javax.swing.JPanel();
        userSelection = new javax.swing.JPanel();
        elegirUsuario = new java.awt.Choice();
        archivoUsuarios = new java.awt.Button();
        agregarUsuario = new java.awt.Button();
        eliminarUsuario = new java.awt.Button();
        signIn = new java.awt.Button();
        guardarUsarios = new java.awt.Button();
        prioridadAltaButton = new javax.swing.JRadioButton();
        prioridadMediaButton = new javax.swing.JRadioButton();
        prioridadBajaButton = new javax.swing.JRadioButton();
        confirmarAgregar = new java.awt.Button();
        cancelarAgregar = new java.awt.Button();
        nombreUsuario = new java.awt.TextField();
        SelectionLabel = new java.awt.Label();
        addUserLabel = new java.awt.Label();
        sistemaPrincipal = new javax.swing.JPanel();
        signOut = new java.awt.Button();
        deleteFromHeap = new java.awt.Button();
        deleteDoc = new java.awt.Button();
        printChoice = new java.awt.Choice();
        button1 = new java.awt.Button();
        choice2 = new java.awt.Choice();
        printMin = new java.awt.Button();
        checkbox1 = new java.awt.Checkbox();
        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        textField3 = new java.awt.TextField();
        button2 = new java.awt.Button();
        printChoice1 = new java.awt.Choice();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Usuarios");
        usersTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treePanel.setViewportView(usersTree);

        displaysPane.addTab("Usuarios y Documentos", treePanel);

        javax.swing.GroupLayout graphDisplayLayout = new javax.swing.GroupLayout(graphDisplay);
        graphDisplay.setLayout(graphDisplayLayout);
        graphDisplayLayout.setHorizontalGroup(
            graphDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );
        graphDisplayLayout.setVerticalGroup(
            graphDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        displaysPane.addTab("Montículo Binario", graphDisplay);

        javax.swing.GroupLayout colaDisplayLayout = new javax.swing.GroupLayout(colaDisplay);
        colaDisplay.setLayout(colaDisplayLayout);
        colaDisplayLayout.setHorizontalGroup(
            colaDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );
        colaDisplayLayout.setVerticalGroup(
            colaDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        displaysPane.addTab("Cola Impresora", colaDisplay);

        panelFondo.setLayout(new java.awt.CardLayout());

        elegirUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        elegirUsuario.setName(""); // NOI18N

        archivoUsuarios.setActionCommand("elegirArchivo");
        archivoUsuarios.setLabel("Cargar Usuarios");
        archivoUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivoUsuariosActionPerformed(evt);
            }
        });

        agregarUsuario.setLabel("Agregar Usuario");
        agregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarUsuarioActionPerformed(evt);
            }
        });

        eliminarUsuario.setLabel("Eliminar Usuario");
        eliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarUsuarioActionPerformed(evt);
            }
        });

        signIn.setLabel("Iniciar Sesion");
        signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInActionPerformed(evt);
            }
        });

        guardarUsarios.setLabel("Guardar Usarios");
        guardarUsarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarUsariosActionPerformed(evt);
            }
        });

        tiposPrioridad.add(prioridadAltaButton);
        prioridadAltaButton.setSelected(false);
        prioridadAltaButton.setText("Prioridad Alta");

        tiposPrioridad.add(prioridadMediaButton);
        prioridadMediaButton.setText("Prioridad Media");

        tiposPrioridad.add(prioridadBajaButton);
        prioridadBajaButton.setText("Prioridad Baja");

        confirmarAgregar.setLabel("Agregar");
        confirmarAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarAgregarActionPerformed(evt);
            }
        });

        cancelarAgregar.setLabel("Cancelar");
        cancelarAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarAgregarActionPerformed(evt);
            }
        });

        nombreUsuario.setName("Nombre del Usuario"); // NOI18N

        addUserLabel.setText("Nombre del usuario:");

        javax.swing.GroupLayout userSelectionLayout = new javax.swing.GroupLayout(userSelection);
        userSelection.setLayout(userSelectionLayout);
        userSelectionLayout.setHorizontalGroup(
            userSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userSelectionLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(archivoUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(guardarUsarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userSelectionLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(userSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userSelectionLayout.createSequentialGroup()
                        .addGroup(userSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userSelectionLayout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(signIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(userSelectionLayout.createSequentialGroup()
                                .addGroup(userSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SelectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(userSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prioridadMediaButton)
                                    .addComponent(prioridadBajaButton)
                                    .addComponent(prioridadAltaButton)))
                            .addGroup(userSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userSelectionLayout.createSequentialGroup()
                                    .addComponent(confirmarAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(71, 71, 71)
                                    .addComponent(cancelarAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(47, 47, 47))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userSelectionLayout.createSequentialGroup()
                                    .addComponent(elegirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(25, 25, 25)
                                    .addComponent(eliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userSelectionLayout.createSequentialGroup()
                        .addComponent(agregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))))
        );
        userSelectionLayout.setVerticalGroup(
            userSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userSelectionLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(userSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(guardarUsarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(archivoUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(agregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(userSelectionLayout.createSequentialGroup()
                        .addComponent(prioridadAltaButton)
                        .addGap(13, 13, 13)
                        .addComponent(prioridadMediaButton)
                        .addGap(16, 16, 16)
                        .addComponent(prioridadBajaButton))
                    .addGroup(userSelectionLayout.createSequentialGroup()
                        .addComponent(addUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SelectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(userSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancelarAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmarAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(userSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(elegirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(signIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );

        panelFondo.add(userSelection, "card2");

        signOut.setLabel("Cerrar Sesión");
        signOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutActionPerformed(evt);
            }
        });

        deleteFromHeap.setLabel("Elimiar documento de la cola");

        deleteDoc.setLabel("Eliminar Documento");

        button1.setLabel("button1");

        printMin.setLabel("Liberar Impresora");

        checkbox1.setLabel("Prioritario");

        textField1.setText("textField1");

        textField2.setText("textField2");

        textField3.setText("textField3");

        button2.setLabel("button2");

        label1.setText("label1");

        javax.swing.GroupLayout sistemaPrincipalLayout = new javax.swing.GroupLayout(sistemaPrincipal);
        sistemaPrincipal.setLayout(sistemaPrincipalLayout);
        sistemaPrincipalLayout.setHorizontalGroup(
            sistemaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sistemaPrincipalLayout.createSequentialGroup()
                .addGroup(sistemaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sistemaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sistemaPrincipalLayout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(printChoice1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(144, 144, 144)
                            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(sistemaPrincipalLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(sistemaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(sistemaPrincipalLayout.createSequentialGroup()
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(76, 76, 76)
                            .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(sistemaPrincipalLayout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(printMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(sistemaPrincipalLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(sistemaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteFromHeap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(sistemaPrincipalLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(signOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(sistemaPrincipalLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(choice2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sistemaPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(printChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sistemaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46))
        );
        sistemaPrincipalLayout.setVerticalGroup(
            sistemaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sistemaPrincipalLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(printMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(sistemaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sistemaPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(sistemaPrincipalLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(sistemaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)))
                .addGroup(sistemaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkbox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printChoice1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(sistemaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteDoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printChoice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(choice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteFromHeap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        panelFondo.add(sistemaPrincipal, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(displaysPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displaysPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        displaysPane.getAccessibleContext().setAccessibleName("tab1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void archivoUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivoUsuariosActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setDialogTitle("Elija un archivo .csv con los usuarios");
        FileNameExtensionFilter restrict = new FileNameExtensionFilter("Only .csv files", "csv");
        fileChooser.addChoosableFileFilter(restrict);
        int r = fileChooser.showOpenDialog(null);
        if (r == JFileChooser.APPROVE_OPTION) {
            try {
                currentFile = new File(fileChooser.getSelectedFile().getAbsolutePath());
                BufferedReader br = new BufferedReader(new FileReader(currentFile));
                String line = br.readLine();
                line = br.readLine();
                while (line != null) {
                    String[] array = line.split(",");
                    Usuario newUser = new Usuario(array[0].strip(), array[1].strip());
                    listaUsuarios.insertFinal(newUser);
                    line = br.readLine();
                }
                setUserOptions();
                br.close();
                setUserDisplay();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_archivoUsuariosActionPerformed

    private void agregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarUsuarioActionPerformed
        // TODO add your handling code here:
        agregarUsuarioVisible(true, "");
    }//GEN-LAST:event_agregarUsuarioActionPerformed

    private void signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInActionPerformed
        // TODO add your handling code here:
        if (elegirUsuario.getItemCount() == 0) {
            SelectionLabel.setText("Eliga un usuario válido");
            return;
        }
        currentUser = listaUsuarios.getElmenetAtIndex(elegirUsuario.getSelectedIndex());
        userSelection.setVisible(false);
        sistemaPrincipal.setVisible(true);
        graficarCola();
    }//GEN-LAST:event_signInActionPerformed

    private void guardarUsariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarUsariosActionPerformed
        
        
        BufferedWriter writer = null;
        try {
            // TODO add your handling code here:
            String newCSV = "usuario, tipo";
            for (Usuario i:listaUsuarios) {
                newCSV += "\n" + i.getName() + ", " + i.getPrioridad();
            }
            if (currentFile == null) {
                JFileChooser dirChooser = new JFileChooser();
                dirChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                
                int r = dirChooser.showOpenDialog(null);
                if (r == JFileChooser.APPROVE_OPTION) {
                    System.out.println(dirChooser.getSelectedFile().getName());
                    currentFile = dirChooser.getSelectedFile();
                    if (!currentFile.getName().toLowerCase().endsWith(".csv")) {
                        currentFile = new File(currentFile.getParentFile(), currentFile.getName() + ".csv");
                    }
                }
            }
            
            writer = new BufferedWriter(new FileWriter(currentFile));
            writer.write(newCSV);
            writer.close();
            
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                writer.close();
                SelectionLabel.setText("Usuarios guardados");
            } catch (IOException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_guardarUsariosActionPerformed

    private void eliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarUsuarioActionPerformed
        // TODO add your handling code here:
        int eliminar = elegirUsuario.getSelectedIndex();
        if (eliminar != -1) {
            Usuario eliminado = listaUsuarios.getElmenetAtIndex(eliminar);
            listaUsuarios.deleteAtIndex(eliminar);
            setUserOptions();
            SelectionLabel.setText("Usuario " + eliminado.getName() + " eliminado");
            setUserDisplay();
        } else {
            SelectionLabel.setText("No se ha elegido a un usuario");
        }
    }//GEN-LAST:event_eliminarUsuarioActionPerformed

    private void cancelarAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarAgregarActionPerformed
        // TODO add your handling code here:
        agregarUsuarioVisible(false, "Se ha cancelado la operación");
    }//GEN-LAST:event_cancelarAgregarActionPerformed

    private void confirmarAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarAgregarActionPerformed
        // TODO add your handling code here:
        if (tiposPrioridad.getSelection() != null && !nombreUsuario.getText().isEmpty()) {
            if (nombreUsuario.getText().contains(" ")) {
                SelectionLabel.setText("Usuario inválido");
                return;
            }
            listaUsuarios.insertFinal(new Usuario(nombreUsuario.getText(), tiposPrioridad.getSelection().getActionCommand()));
            agregarUsuarioVisible(false, "Usuario " + nombreUsuario.getText() + " agregado");
            setUserOptions();
            setUserDisplay();
        } else {
            SelectionLabel.setText("Rellene todos los campos");
        }
    }//GEN-LAST:event_confirmarAgregarActionPerformed

    private void signOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutActionPerformed
        // TODO add your handling code here:
        sistemaPrincipal.setVisible(false);
        userSelection.setVisible(true);
    }//GEN-LAST:event_signOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        System.setProperty("org.graphstream.ui", "swing");
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                Clock timer = Clock.systemDefaultZone();
//                new GUI().setVisible(true);
//                BinaryHeap<Documento> colaImpresion = new BinaryHeap(20);
//                Lista<Usuario> listaUsuarios = new Lista();
//                Graph monticulo = new SingleGraph("Cola de prioridad");
                GUI app = new GUI();
                app.setSize(780, 420);
                app.setDefaultCloseOperation(GUI.EXIT_ON_CLOSE);
                app.setVisible(true);
                app.setLocationRelativeTo(null);
                
//                GraphicsEnvironment graphics = GraphicsEnvironment.getLocalGraphicsEnvironment();
//                GraphicsDevice device = graphics.getDefaultScreenDevice();
//                device.setFullScreenWindow(app);
            }
        });
    }
    
    public void graficarCola() {
        monticulo.clear();
        ListaArray<BHNode<Documento>> heap = colaImpresion.getHeap();
        for (int i = 0; i < heap.getSize(); i++) {
            Documento doc = heap.getElmenetAtIndex(0).getElement();
            if (monticulo.getNode(doc.getName()) == null) {
                monticulo.addNode(doc.getName());
            }
            Node actual = monticulo.getNode(doc.getName());
            actual.setAttribute("ui.label", doc.getName()+"."+doc.getType()+"\n"+doc.getSize()+"hojas");
            if (colaImpresion.leftChild(i) < colaImpresion.getSize()) {
                Documento leftSon = heap.getElmenetAtIndex(colaImpresion.leftChild(i)).getElement();
                monticulo.addEdge(doc.getName()+leftSon.getName(), doc.getName(), leftSon.getName());
            }
            if (colaImpresion.rightChild(i) < colaImpresion.getSize()) {
                Documento rightSon = heap.getElmenetAtIndex(colaImpresion.rightChild(i)).getElement();
                monticulo.addEdge(doc.getName()+rightSon.getName(), doc.getName(), rightSon.getName());
            }
        }
        
        Viewer viewer = new SwingViewer(monticulo, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        View view = viewer.addDefaultView(false);
        view.openInAFrame(false);
        graphDisplay.setLayout(new BorderLayout());
        graphDisplay.add((Component)view);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label SelectionLabel;
    private java.awt.Label addUserLabel;
    private java.awt.Button agregarUsuario;
    private java.awt.Button archivoUsuarios;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button cancelarAgregar;
    private java.awt.Checkbox checkbox1;
    private java.awt.Choice choice2;
    private javax.swing.JPanel colaDisplay;
    private java.awt.Button confirmarAgregar;
    private java.awt.Button deleteDoc;
    private java.awt.Button deleteFromHeap;
    private javax.swing.JTabbedPane displaysPane;
    private java.awt.Choice elegirUsuario;
    private java.awt.Button eliminarUsuario;
    private javax.swing.JPanel graphDisplay;
    private java.awt.Button guardarUsarios;
    private java.awt.Label label1;
    private java.awt.TextField nombreUsuario;
    private javax.swing.JPanel panelFondo;
    private java.awt.Choice printChoice;
    private java.awt.Choice printChoice1;
    private java.awt.Button printMin;
    private javax.swing.JRadioButton prioridadAltaButton;
    private javax.swing.JRadioButton prioridadBajaButton;
    private javax.swing.JRadioButton prioridadMediaButton;
    private java.awt.Button signIn;
    private java.awt.Button signOut;
    private javax.swing.JPanel sistemaPrincipal;
    private java.awt.TextArea textArea1;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private javax.swing.ButtonGroup tiposPrioridad;
    private javax.swing.JScrollPane treePanel;
    private javax.swing.JPanel userSelection;
    private javax.swing.JTree usersTree;
    // End of variables declaration//GEN-END:variables
}
